version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"

    postgres:
        container_name: pg_container
        image: postgres:latest
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"
volumes:
    postgres_volume_local:
        external: true